AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function to delete unattached EBS volumes with aws mgn tags.

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - ec2:DescribeVolumes
                  - ec2:DeleteVolume
                Resource: '*'

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3

          def lambda_handler(event, context):
              ec2 = boto3.client('ec2')
              
              response = ec2.describe_volumes(Filters=[
                  {'Name': 'tag:Name', 'Values': ['AWS Application Migration Service Replication Server']},
              ])
              
              for volume in response['Volumes']:
                  volume_id = volume['VolumeId']
                  attachments = volume['Attachments']
                  
                  if not attachments:
                      print(f"Deleting unattached volume: {volume_id}")
                      ec2.delete_volume(VolumeId=volume_id)
                  else:
                      print(f"Volume {volume_id} is still attached.")
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
